# Generated by Django 5.2.1 on 2025-05-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('diretor', models.CharField(max_length=100)),
                ('data_lancamento', models.DateField()),
                ('capa', models.ImageField(upload_to='capas/')),
                ('background', models.ImageField(upload_to='backgrounds/')),
            ],
        ),
    ]
