# Generated by Django 5.2.1 on 2025-05-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo',
            old_name='diretor',
            new_name='estudio',
        ),
    ]
